### ISSUE TITLE
Release Spongy Castle update based on v1.50 release of Bouncy Castle

### ISSUE THREAD

**Issue by rtyley** [rtyley/spongycastle#1]
Bouncy Castle v1.50 was released on 3rd December 2013:

http://www.bouncycastle.org/devmailarchive/msg13438.html
http://www.bouncycastle.org/releasenotes.html

(this issue corresponds to https://github.com/rtyley/spongycastle-old/issues/14 from the legacy Spongy Castle repo)

**Comment by rtyley** [comment]
Spongy Castle v1.50.0.0 (from BC v1.50) has been released - see the release notes here:

https://github.com/rtyley/spongycastle/releases/tag/sc-v1.50.0.0

@abeluck @martijno @filipebatista @dschuermann @caiobalthazar, it would be great if you could take a look at this release and give feedback on how it works for you, well or otherwise.

**Comment by dschuermann** [comment]
Thanks for your work! We will start integrating the new version into OpenPGP Keychain and communicate back if problems occur.

**Comment by dschuermann** [comment]
Thanks again. Our build is working fine with Spongy Castle 1.50. Because I want to build everything from source, I added the sources of Spongy Castle to our repo and added the modules as project dependencies to our gradle builds and everything works fine. see https://github.com/dschuermann/openpgp-keychain/commit/6ae99cc6cbdf41c0e500f611d4133e16bd7a2113

**Comment by rtyley** [comment]
That's good to hear! Much appreciated @dschuermann - incidentally, just wondered if you considered using a git-submodule instead of the bulk-copy?

**Comment by dschuermann** [comment]
I am considering git submodules or git subtree, but due to problems with git submodules (see for example http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/) I have deferred the decision ;)

I want to keep my project as easy to build as possible for newcomers.

**Comment by ghost** [comment]
Hi Tyley, I was only now able to test the update. But I got good news: it all worked fine. I'm using EC crypto, CMS signing and validation and also a little bit of hashing, all through the JCE provider and pkix module. None of my tests failed and the apps seem to be working as well as before. Thank you very much for your contributions!
