### ISSUE TITLE
2.x version (IllegalArgumentException not an OID)

### ISSUE THREAD

**Issue by d2callpod** [rtyley/spongycastle#10]
I have an issue reported by a user where they are getting an IllegalArgumentException for an OID. I see a number of fixes in the 2.x versions of Bouncy Castle for OID parsing.

Are there plans to release a 2.x version of SpongyCastle?

P.S. User stack trace attached. Apologies that it's a screen shot that's all I have at this time.
![spongycastle oid exception](https://cloud.githubusercontent.com/assets/4429507/6152113/731f8efe-b1cf-11e4-8ee7-06fca37afcfb.jpg)

**Comment by rtyley** [comment]
SpongyCastle releases are usually made sometime after the Bouncy Castle is released here:

https://www.bouncycastle.org/latest_releases.html

(also, when the release is tagged here: https://github.com/bcgit/bc-java/releases )

...it takes a while to fix all the broken tests,etc, once the code has dropped.

I don't see any sign of a 2.x release, and don't closely follow the BouncyCastle mailing list, so where do you see signs of a 2.x release?

**Comment by d2callpod** [comment]
I was looking here https://www.bouncycastle.org/releasenotes.html. Is that planned releases?

**Comment by rtyley** [comment]
If you re-read that page, you'll see that you've misread it because of the
confusing paragraph numbering.

**Comment by d2callpod** [comment]
Ahh, yes I see.

Thanks
