### ISSUE TITLE
Bouncy Castle 1.52

### ISSUE THREAD

**Issue by dschuermann** [rtyley/spongycastle#13]
Hey @rtyley 
it's time again ;)
Bouncy Castle has been tagged as 1.52: https://github.com/bcgit/bc-java/releases/tag/r1rv52

**Comment by brcolow** [comment]
Are there any plans for spongycastle to merge upstream changes?

**Comment by rtyley** [comment]
I started up a new branch when https://github.com/bcgit/bc-java/releases/tag/r1rv52 came out, but getting the bouncycastle test suite to pass with each new release is always a major investment of time. As soon as there's a green build on https://travis-ci.org/rtyley/spongycastle/branches, I'll do a release. I'm pretty busy.

**Comment by rtyley** [comment]
Spongycastle v1.52.0.0 has now been released: https://github.com/rtyley/spongycastle/releases/tag/sc-v1.52.0.0

**Comment by brcolow** [comment]
:+1:

**Comment by brcolow** [comment]
Thank you very much for doing this - just wanted to respond back and say that my tests were all green =).

**Comment by rtyley** [comment]
> Thank you very much for doing this - just wanted to respond back and say that my tests were all green =).

That's good!
