### ISSUE TITLE
BouncyCastle 1.53 is out

### ISSUE THREAD

**Issue by NumberFour8** [rtyley/spongycastle#16]
Is there gonna be an update to new BouncyCastle 1.53? This version contains changes in SHA3, which break compatibility with older versions. Its impossible to use BC 1.53 against SC 1.52 without altering the app code.

**Comment by rtyley** [comment]
Thanks for the heads-up @NumberFour8 ! I've released Spongy Castle v1.53.0.0 to Maven Central and you should be able to download it now:

https://github.com/rtyley/spongycastle/releases/tag/sc-v1.53.0.0

**Comment by NumberFour8** [comment]
Great! Thanks for the quick reply and release!
