### ISSUE TITLE
Spongy Castle KeyPairGenerator extremely slow on Android M

### ISSUE THREAD

**Issue by KubebatHaMachatz** [rtyley/spongycastle#17]
Hi,

When using Spongy Castle KeyPairGenerator , the statement "keyGen.generateKeyPair();" takes extremely long time to execute on Android M.

It takes around 12-13 seconds for this line to execute on Android 6 devices . in comparison - It takes 2-3 seconds on previous Android versions using the exact same libraries.

A sample Android Studio project is attached.

any help in getting better performance 

would be greatly appreciated.

sample code :

```
    KeyPair keyPair = null;
    KeyPairGenerator keyGen = null;
    keyGen = KeyPairGenerator.getInstance("RSA", "BC");
    keyGen.initialize(2048);

    keyPair = keyGen.generateKeyPair(); <-This is the problematic statement

    byte[] privateKeyBytes = keyPair.getPrivate().getEncoded();
    String privateKey = new String(Base64.encode(privateKeyBytes, Base64.NO_WRAP));
    PublicKey signaturePublicKey = keyPair.getPublic();
```

**Comment by martijno** [comment]
Wouldn't that have to be "SC" instead of "BC" for the provider name?

**Comment by daniele-athome** [comment]
You should mention on what device you're running this from. It is often an entropy issue.

**Comment by KubebatHaMachatz** [comment]
Tested on two devices - Nexus 5X  and  Nexus 5.
Changing  
keyGen = KeyPairGenerator.getInstance("RSA", "BC");
To
keyGen = KeyPairGenerator.getInstance("RSA", "SC");

seems to have done the trick and the code runs faster (~1 second for the statement to run). 

I guess that keyGen = KeyPairGenerator.getInstance("RSA", "BC") was calling a different provider.

Sorry for your trouble and thank you for your help.

Regards,
Dan
