### ISSUE TITLE
BouncyCastle 1.55 is out

### ISSUE THREAD

**Issue by NumberFour8** [rtyley/spongycastle#28]
Just for the record, BouncyCastle 1.55 has been released :) 
Can we expect SpongyCastle 1.55 to be rolled out anytime soon?

Many thanks!

**Comment by rtyley** [comment]
Should be soon - I'm just looking at the CI problems now:

https://travis-ci.org/rtyley/spongycastle/builds/153765517

**Comment by connyduck** [comment]
Any Update on this? Meanwhile, BouncyCastle 1.56 is out.

**Comment by akumaigorodski** [comment]
Is this repo still alive?

**Comment by rtyley** [comment]
Please see https://github.com/rtyley/spongycastle/issues/34 for an update, and leave feedback there.
