### ISSUE TITLE
1.58 released

### ISSUE THREAD

**Issue by akumaigorodski** [rtyley/spongycastle#36]
1.58 is out and once again my project needs it since as it turned out 1.56 has introduced some breaking changes which were properly fixed in 1.58. Are there plans to release spongycastle 1.58 any time soon?

Once again I'm willing to make a 0.1 BTC donation so feel free to provide an address.

**Comment by rtyley** [comment]
Many thanks for continuing your support @btcontract - my bitcoin address is 15imdX4gCrbqUot2ukzT99d4pyENKQiniD - I should be able to take a look at releasing spongycastle 1.58 over the next few days.

**Comment by rtyley** [comment]
Spongy Castle v1.58 is now released: https://github.com/rtyley/spongycastle/releases/tag/sc-v1.58.0.0 :sparkles:
