### ISSUE TITLE
Version of bc 1.51?

### ISSUE THREAD

**Issue by mikehearn** [rtyley/spongycastle#5]
Hiya,

BC 1.51 is now in final beta and we really need the performance improvements in bitcoinj. I was wondering if you'll have time to upgrade to the newest version any time soon? If not, how hard is it for us to do that?

**Comment by rtyley** [comment]
> I was wondering if you'll have time to upgrade to the newest version any time soon?

I took a look at building off the most recent master (cebc7ce74) tonight, it doesn't look too bad. There's the usual annoying thing where if you check out BouncyCastle's master branch and just run `gradle test`, a bunch of tests fail:

```
$ gradle test
...
org.bouncycastle.crypto.test.AllTests > testCrypto FAILED
    junit.framework.AssertionFailedError at AllTests.java:22

org.bouncycastle.crypto.tls.test.TlsTestCase > warning FAILED
    junit.framework.AssertionFailedError

org.bouncycastle.crypto.tls.test.DTLSTestCase > warning FAILED
    junit.framework.AssertionFailedError
```

Sigh. Every time I do a release, I do my best to get their test suite to run, and it generally involves fixing-up a bunch of broken tests. Maybe I can persuade those guys to start using Travis for this release...

**Comment by mikehearn** [comment]
Thanks for looking at this, it's really helpful. Basically we switched to HD wallets in the new bitcoinj and as a result do way more EC math than before. Without the new version wallets now take too long to create and it causes an ANR. The new BC is fast enough that we can do the calculations on the UI thread and get away with it, meaning we can avoid some complicated threading.

**Comment by mikehearn** [comment]
Hi Roberto, anything we can do to help here? Our own test suite is pretty comprehensive and we don't use TLS, so I'm not worried about the test failures.

**Comment by rtyley** [comment]
The [SpongyCastle 1.51.0.0](https://github.com/rtyley/spongycastle/releases/tag/sc-v1.51.0.0) release (based on BouncyCastle [r1rv51](https://github.com/bcgit/bc-java/releases/tag/r1rv51)) has very recently been pushed to Maven Central (was halfway uploaded when you sent that message!) and is now available for download, eg:

http://repo1.maven.org/maven2/com/madgag/spongycastle/core/1.51.0.0/

Please do report back and let me know if your test suite succeeds or fails.

**Comment by mikehearn** [comment]
All tests pass both before and after upgrading to accelerated secp256k1. Sure, bitcoinj only really stresses the EC math parts of BC which is only a small component, but it seems to be working. Thanks!!

**Comment by rtyley** [comment]
Great!
