### ISSUE TITLE
Javadoc upload

### ISSUE THREAD

**Issue by mikehearn** [rtyley/spongycastle#6]
It'd be nice if you could generate the javadocs and upload them e.g. to github sites. Then I can tell my own javadoc run to use your site as a link so where my API exposes Spongy/BouncyCastle stuff, it can auto link to the right javadocs.

**Comment by rtyley** [comment]
Javadoc is generated and pushed to maven central as a jar, but there's
currently no directly-accessible HTML version you can point a browser at.

The build is gradle-based, I presume there's a plugin or something for
pushing javadoc as part of a release? If you can dig out the config, a pull
request would be much appreciated.

**Comment by mikehearn** [comment]
As far as I know, just unzipping the javadoc jar and upload the contents to the web somewhere is enough. Not sure how to automate that with gradle. I guess with github sites it's just an "unzip; git add; git commit".

**Comment by rtyley** [comment]
Spongycastle Javadoc can now be accessed online at:

http://www.javadoc.io/doc/com.madgag.spongycastle/core/1.52.0.0

or 

https://static.javadoc.io/com.madgag.spongycastle/core/1.52.0.0/index.html

...for HTTPS. This service isn't hosted by me, but seems legit, and awesome.

**Comment by rtyley** [comment]
There's now a supported URL for HTTPS access:

https://www.javadoc.io/doc/com.madgag.spongycastle/core/1.52.0.0

Thanks to [Zhu](https://plus.google.com/112390507664956127732) for letting me know.
